#!/bin/bash
echo -n "enter the content of the keystore file for the worker"
read keystore
echo -n "enter ENDPOINT WSS mainnet info"
read infura
cd $HOME
sudo apt update
sudo apt upgrade -y
sudo apt install python3-dev build-essential libffi-dev python3-pip python3-venv -y
python3 -m venv ./nucypher-venv
source nucypher-venv/bin/activate
pip3 install -U wheel
pip3 install -U nucypher
mkdir -p /$HOME/.ethereum/keystore
echo $keystore > /$HOME/.ethereum/keystore/wallet1
source nucypher-venv/bin/activate
nucypher ursula init --signer keystore:///$HOME/.ethereum/keystore --provider $infura
echo -e "\e[34mNode installed with the following parameters:\nkeystore \e[32m$keystore\n\e[34mEndPoint \e[32m$infura\e[0m"
echo "Want to run a node as a service (y/n)?"
read answer
if [ "$answer" == "y" ];then echo -n "enter the password for the worker's Keystore file "
read keystorepassw
echo -n "enter Ursula's Keyring password "
read keyring
echo -e "[Unit]\nDescription="NuCypher Node"\n[Service]\nUser=$USER\nType=simple\nEnvironment="NUCYPHER_WORKER_ETH_PASSWORD=$keystorepassw"\nEnvironment="NUCYPHER_KEYRING_PASSWORD=$keyring"\nExecStart=$HOME/nucypher-venv/bin/nucypher ursula run\nRestart=always\nRestartSec=3\n[Install]\nWantedBy=multi-user.target" > nucypher.txt
sudo mv nucypher.txt /etc/systemd/system/nucypher.service
sudo systemctl daemon-reload
sudo systemctl enable nucypher
sudo systemctl start nucypher
echo "Ursula launched as a service"
echo -e "you can check the status with the command\nsudo journalctl -u nucypher -f" 
else echo -e "\e[34mYou can run Ursula \ nCommands to run:\n\e[32msource nucypher-venv/bin/activate\nnucypher ursula run\e[0m"
exit 0
fi
exit 0
